In [1]:
# scipi liner algebra
import numpy as np
from scipy import linalg

A = np.array([[1, 1], [2, 3]])
print("A array")
print(A)

b = np.array([[1], [2]])
print("b array")
print(b)

solution = np.linalg.solve(A, b) 
print("solution ")
print(solution)

# validate results
print("validation of solution (should be a 0 matrix)")
print(A.dot(solution) - b)

A array
[[1 1]
 [2 3]]
b array
[[1]
 [2]]
solution 
[[ 1.]
 [ 0.]]
validation of solution (should be a 0 matrix)
[[ 0.]
 [ 0.]]
